let wight = parseInt(prompt("chieu rong"))
let hight = parseInt(prompt("chieu dai"))
let area = wight*hight
document.write('Enter wight')
document.write('<br>' )
document.write(wight)
document.write('<br>' )
document.write('Enter hight' )
document.write('<br>' )
document.write(hight)
    document.write('<br>')
document.write('this is area')
document.write('<br>')
document.write( area )
